# Meta information about Phrozn
---
name: Phrozn
summary: Static web-site generator for PHP.
description: &desc Phrozn is an extremely flexible static site generator for PHP.
version: &ver "1.0DEV"
stability: beta
author: Victor Farazdagi, Povilas Balzaraviƒçius

# executable customization
use_ansi_colors: false

command:
    name: /usr/bin/phrozn
    description: *desc
    version: *ver
    add_help_option: false
    options:
        help:
            short_name:     -h
            long_name:      --help
            description:    Show this help message
            action:         StoreTrue
