# phr bundle 
---
command:
    name: &name bundle
    aliases: 
    description: &desc Phrozn bundles manager
    commands:
        list:
            name: list
            description: List bundles
            options:
                all:
                    short_name:  -a
                    long_name:   --all
                    doc_name:    -a [--all]
                    description: List all bundles
                    action:      StoreTrue 
                    default:     false
                installed:
                    short_name:  -i
                    long_name:   --installed
                    doc_name:    -i [--installed]
                    description: List installed bundles
                    action:      StoreTrue 
                    default: false
                available:
                    short_name:  -n
                    long_name:   --not-installed
                    doc_name:    -n [--not-installed]
                    description: List not installed (available) bundles
                    action:      StoreTrue 
                    default:     false
            arguments:
                bundle:
                    help_name: bundle
                    description: Bundle name, path or URL
                    optional: true
        info:
            name: info
            description: Display bundle information
            arguments:
                bundle:
                    help_name: bundle
                    description: Bundle name, path or URL
                    optional: false
        apply:
            name: apply
            description: Apply given bundle to Phrozn project
            arguments:
                bundle:
                    help_name: bundle
                    description: Bundle name, path or URL
                    optional: false
                path:
                    help_name: path
                    description: Path to apply bundle to
                    optional: true
        clobber:
            name: clobber
            description: Remove given bundle from the project
            arguments:
                bundle:
                    help_name: bundle
                    description: Bundle name, path or URL
                    optional: false

# callback
callback: [Bundle, execute]

# documentation
docs:
    name: bundle
    summary: *desc
    description: |
        For flexibility, various parts of Phrozn ecosystem 
        can be combined together into so-called bundles, which can be 
        applied to project.

        Bundle manager allows you to add/remove/update bundles easily.

        If BUNDLE is the name of the bundle, then officially supported bundle is 
        assumed. Otherwise you can specify path (or URL) to bundle file.

    extradesc: |
        Essentially bundles are directories with pre-defined structure packed into
        Phar achrives. Phrozn takes care to extract and copy files into the given
        project. It also keeps track of installed bundles so that they can be 
        easily removed.

    usage: |
        %bphrozn%n %gbundle%n COMMAND [BUNDLE]
        %bphrozn%n %gbundle%n info BUNDLE
        %bphrozn%n %gbundle%n list [-i|-a|-p] [BUNDLE]
        %bphrozn%n %gbundle%n apply BUNDLE
        %bphrozn%n %gbundle%n clobber BUNDLE
    examples: |
        Get information about given bundle:
        %bphrozn%n %gbundle%n info BUNDLE
       
        List all officially availble bundles:
        %bphrozn%n %gbundle%n list
        %bphrozn%n %gbundle%n list -a
        %bphrozn%n %gbundle%n list --all

        List installed bundles:
        %bphrozn%n %gbundle%n list --i
        %bphrozn%n %gbundle%n list --installed

        List not installed (available) bundles:
        %bphrozn%n %gbundle%n list -p
        %bphrozn%n %gbundle%n list --not-installed

        To apply bundle from official repository:
        %bphrozn%n %gbundle%n apply BUNDLE

        To apply test processor used in docs (http://bit.ly/icTc35):
        %bphrozn%n %gbundle%n apply processor.test

        To apply bundle located in archive:
        %bphrozn%n %gbundle%n apply /path/to/processor.test.phar

        To remove bundle:
        %bphrozn%n %gbundle%n clobber BUNDLE


